### PR TITLE
ScoreboardM Project

### PR DESCRIPTION
**Pull request by GamerFile**

### CODE REVIEW

**Comment by JaylyDev** [comment]
Thanks for the PR. Could you please update your script file so the header matches the format:

```js
// Script example for ScriptAPI
// Author: GamerFile <https://github.com/GamerFile>
// Project: https://github.com/JaylyDev/ScriptAPI
```

Also I believe the script has some errors. This must be fixed.
```
scripts/ScoreboardM/index.js(93,21): error TS2322: Type 'number' is not assignable to type '{ setObj: (id: string, v: string) => ...; hasObj: (id: string) => boolean; getObj: (id: string) => any; newObj: (id: string, v: string) => ...; setScore: (target: any, Objective: string, score: number) => ...; ... 7 more ...; setDisplaySlot: (id: string, opt: any) => ...; }'.
scripts/ScoreboardM/index.js(96,13): error TS2322: Type 'number' is not assignable to type '{ setObj: (id: string, v: string) => ...; hasObj: (id: string) => boolean; getObj: (id: string) => any; newObj: (id: string, v: string) => ...; setScore: (target: any, Objective: string, score: number) => ...; ... 7 more ...; setDisplaySlot: (id: string, opt: any) => ...; }'.
```

**Comment by GamerFile** [comment]
Ye i see 
I'll fix

**Comment by JaylyDev** [comment]
@bot174 What's up with those workflows?

**Comment by bot174** [comment]
the name has capital letters

**Review by JaylyDev — APPROVED** [review]

**Pull request merged**
